var file = argument0
var type = argument1
var wsize = argument2, hsize = argument3;
var append = "";

if (global.chunk)
    append = " (Split into "+string(global.chunkval[0])+"x"+string(global.chunkval[1])+" chunks)"

FS_file_text_write_string(file, "// Generated by Nintendo 64 Texture Converter");
FS_file_text_writeln(file);
FS_file_text_write_string(file, "// By buu342");
FS_file_text_writeln(file);
FS_file_text_write_string(file, "// Size = "+string(wsize)+"x"+string(hsize)+append);
FS_file_text_writeln(file);
FS_file_text_write_string(file, "// Type = "+type);
FS_file_text_writeln(file);
