var char;
var whitelist;

char = argument0;
whitelist[0] = '0'
whitelist[1] = '1'
whitelist[2] = '2'
whitelist[3] = '3'
whitelist[4] = '4'
whitelist[5] = '5'
whitelist[6] = '6'
whitelist[7] = '7'
whitelist[8] = '8'
whitelist[9] = '9'
whitelist[10] = 'a'
whitelist[11] = 'b'
whitelist[12] = 'c'
whitelist[13] = 'd'
whitelist[14] = 'e'
whitelist[15] = 'f'
whitelist[16] = 'g'
whitelist[17] = 'h'
whitelist[18] = 'i'
whitelist[19] = 'j'
whitelist[20] = 'k'
whitelist[21] = 'l'
whitelist[22] = 'm'
whitelist[23] = 'n'
whitelist[24] = 'o'
whitelist[25] = 'p'
whitelist[26] = 'q'
whitelist[27] = 'r'
whitelist[28] = 's'
whitelist[29] = 't'
whitelist[30] = 'u'
whitelist[31] = 'v'
whitelist[32] = 'w'
whitelist[33] = 'x'
whitelist[34] = 'y'
whitelist[35] = 'z'
whitelist[36] = 'A'
whitelist[37] = 'B'
whitelist[38] = 'C'
whitelist[39] = 'D'
whitelist[40] = 'E'
whitelist[41] = 'F'
whitelist[42] = 'G'
whitelist[43] = 'H'
whitelist[44] = 'I'
whitelist[45] = 'J'
whitelist[46] = 'K'
whitelist[47] = 'L'
whitelist[48] = 'M'
whitelist[49] = 'N'
whitelist[50] = 'O'
whitelist[51] = 'P'
whitelist[52] = 'Q'
whitelist[53] = 'R'
whitelist[54] = 'S'
whitelist[55] = 'T'
whitelist[56] = 'U'
whitelist[57] = 'V'
whitelist[58] = 'W'
whitelist[59] = 'X'
whitelist[60] = 'Y'
whitelist[61] = 'Z'
whitelist[62] = '_'

var i;
for (i=0; i<62; i+=1)
    if (whitelist[i] == char)
        return ""   
return char
